sliders = WAVE_STRENGTH WAVE_SPEED DIFFUSE_BRDF VANILLA_METAL_CONPENSATE sun_illuminance 

screen.columns = 2
screen = \
[Debuge] <empty> \
[World]  <empty> \

    screen.Debuge.columns = 1
    screen.Debuge = [PBR]
        screen.PBR.columns = 1
        screen.PBR = FRESNEL DIFFUSE_BRDF FORCIBLY_ENABLE_PBR FORCIBLY_ENABLE_VANILLA_PBR VANILLA_METAL_CONPENSATE

    screen.World.columns = 1
    screen.World = [Wave] [LightColor]
        screen.Wave.columns = 1
        screen.Wave = WAVE_STRENGTH WAVE_SPEED

        screen.LightColor.columns = 1
        screen.LightColor = [SunColor] [MoonColor]
            screen.SunColor.columns = 1
                screen.SunColor = sun_illuminance Sun_temp sunColorR sunColorG sunColorB
            screen.MoonColor.columns = 1
                screen.MoonColor = moon_illuminance Moon_temp moonColorR moonColorG moonColorB

