sliders = WAVE_STRENGTH WAVE_SPEED DIFFUSE_BRDF

screen.columns = 2
screen = \
[Debuge] <empty> \
[World]  <empty> \

    screen.Debuge.columns = 1
    screen.Debuge = [PBR]
        screen.PBR.columns = 1
        screen.PBR = FRESNEL DIFFUSE_BRDF FORCIBLY_ENABLE_PBR

    screen.World.columns = 1
    screen.World = [Wave]
        screen.Wave.columns = 1
        screen.Wave = WAVE_STRENGTH WAVE_SPEED

